### ISSUE TITLE
SQLite error with locale en_ZA

### ISSUE THREAD

**Issue by valllllll2000** [amplitude/Amplitude-Android#106]
Amplitude version 2.7.1:
I have seen the following issue on my LG G3 with Android 5.0, it happened once when my locale was en_ZA, then I changed the locale to en_US and never got the error again but here it is:

```
05-19 16:23:10.688 2755-2755/com.abtnprojects.ambatana:leakcanary E/SQLiteDatabase: Failed to open database '/data/data/com.packagename/databases/com.amplitude.api'.
                                                                                    android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.packagename/databases/com.amplitude.api' to 'en_ZA'.
                                                                                        at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:398)
                                                                                        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
                                                                                        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                                        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                                        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                                        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                                        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:907)
                                                                                        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:892)
                                                                                        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:795)
                                                                                        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1213)
                                                                                        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267)
                                                                                        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                                                        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                                        at com.amplitude.api.DatabaseHelper.insertOrReplaceKeyValueToTable(DatabaseHelper.java:127)
                                                                                        at com.amplitude.api.DatabaseHelper.insertOrReplaceKeyValue(DatabaseHelper.java:116)
                                                                                        at com.amplitude.api.AmplitudeClient.setUserId(AmplitudeClient.java:805)
                                                                                        at 

com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
                                                                                     Caused by: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
                                                                                        at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
                                                                                        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:560)
                                                                                        at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:371)
                                                                                        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218) 
                                                                                        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193) 
                                                                                        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463) 
```

**Comment by djih** [comment]
@valllllll2000 thanks for reporting. It looks like the solution is to open the database file with an extra flag that ignores locale: https://github.com/Raizlabs/DBFlow/issues/440, except that our DatabaseHelper class extends the Android SQLiteOpenHelper class that opens the database file for us

**Comment by ipereziriarte** [comment]
Thanks @djih @valllllll2000 is my team mate. I'll follow this issue while she's on holidays 👍

**Comment by alexwinston** [comment]
Any progress on this issue?  We are seeing this as well.
