### ISSUE TITLE
AmplitudeClient#setOptOut() blocks the main thread

### ISSUE THREAD

**Issue by austynmahoney** [amplitude/Amplitude-Android#113]
[`AmplitudeClient#setOptOut()`](https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/AmplitudeClient.java#L426) runs on the main thread.

I call this method directly after `initialize()`, so it looks like the database has not been created yet due to a race condition from the backgrounded `initialize()` call. This can cause the main thread to be blocked for around 150ms on start. On subsequent calls (once the database has been created), it can still take around 70ms on an emulator.

Any method that has database calls should probably be put into some kind of background task queue. That way they are executed in order, and do not block the main thread.

```
StrictMode policy violation; ~duration=150 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1263)
                  at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:292)
                  at java.io.File.isDirectory(File.java:522)
                  at android.app.ContextImpl.validateFilePath(ContextImpl.java:1931)
                  at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:566)
                  at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
                  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                  at com.amplitude.api.DatabaseHelper.insertOrReplaceKeyValueToTable(DatabaseHelper.java:127)
                  at com.amplitude.api.DatabaseHelper.insertOrReplaceKeyLongValue(DatabaseHelper.java:121)
                  at com.amplitude.api.AmplitudeClient.setOptOut(AmplitudeClient.java:432)
```

**Comment by djih** [comment]
@austynmahoney Thanks for reporting, this was supposed to have also been updated with the latest version. Will patch and release a new version

**Comment by djih** [comment]
@austynmahoney thanks again for reporting. The fix has been pushed with [v2.9.1](https://github.com/amplitude/Amplitude-Android/releases/tag/v2.9.1), it will show up in Maven within a few hours

**Comment by austynmahoney** [comment]
@djih Thanks!

Quick unrelated question, are you building using Android Studio? The project won't import properly using the maven configuration in the repo.

**Comment by austynmahoney** [comment]
Sorry I must not have been clear. I'm looking at building the project from source in Android Studio (I may be contributing a PR).

**Comment by djih** [comment]
@austynmahoney oh you need to build with `ant`, there's a `build.xml` file in the base directory. You would run like `ant clean; ant build; ant test;` etc

**Comment by austynmahoney** [comment]
Thanks.

With the build being in Ant and not Gradle, no PR from me. Too much of a hassle getting it imported into Android Studio.
