### ISSUE TITLE
Rare crash on getCountryForLocation

### ISSUE THREAD

**Issue by fede1608** [amplitude/Amplitude-Android#119]
This is the stacktrace I got from crashlytics:

```
Fatal Exception: java.lang.IllegalArgumentException: latitude == 1.02469E7
       at android.location.Geocoder.getFromLocation(Geocoder.java:126)
       at com.amplitude.api.DeviceInfo$CachedInfo.getCountryFromLocation(DeviceInfo.java:137)
       at com.amplitude.api.DeviceInfo$CachedInfo.getCountry(DeviceInfo.java:115)
       at com.amplitude.api.DeviceInfo$CachedInfo.(DeviceInfo.java)
       at com.amplitude.api.DeviceInfo$CachedInfo.(DeviceInfo.java)
       at com.amplitude.api.DeviceInfo.getCachedInfo(DeviceInfo.java:260)
       at com.amplitude.api.DeviceInfo.prefetch(DeviceInfo.java:266)
       at com.amplitude.api.AmplitudeClient$2.run(AmplitudeClient.java:284)
       at com.amplitude.api.AmplitudeClient.runOnLogThread(AmplitudeClient.java:1757)
       at com.amplitude.api.AmplitudeClient.initializeDeviceInfo(AmplitudeClient.java:279)
       at com.amplitude.api.AmplitudeClient.access$100(AmplitudeClient.java:40)
       at com.amplitude.api.AmplitudeClient$1.run(AmplitudeClient.java:231)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

I was using Amplitude 2.8.0, I'm gonna update to the latest version now (2.9.2), but the changelog doesn't say anything about fixing this issue.

**Comment by djih** [comment]
@fede1608 thanks for reporting. Latitude values are expected to be between -90 and 90, so the fact that it was 1.02E7 means the device's GPS readings were corrupted or something for that one reading. We will update the SDK to gracefully handle that case

**Comment by djih** [comment]
@fede1608 we now handle the crash in v2.10.0 thanks again for reporting
