### ISSUE TITLE
NPE when calling AmplitudeClient.initialize()

### ISSUE THREAD

**Issue by yihuaqi** [amplitude/Amplitude-Android#139]
We're using v2.13.3 and found a consistent crash on a User who is using STUDIO M HD with Android 5.

It's another example of an improperly implemented DefaultDatabaseErrorHandler.

Here's the stacktrace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.FileOutputStream.close()' on a null object reference
       at android.database.DefaultDatabaseErrorHandler.fileCopy(DefaultDatabaseErrorHandler.java:81)
       at android.database.DefaultDatabaseErrorHandler.onCorruption(DefaultDatabaseErrorHandler.java:99)
       at android.database.sqlite.SQLiteDatabase.onCorruption(SQLiteDatabase.java:352)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:823)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1283)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
       at com.amplitude.api.DatabaseHelper.getValueFromTable(DatabaseHelper.java:222)
       at com.amplitude.api.DatabaseHelper.getValue(DatabaseHelper.java:211)
       at com.amplitude.api.AmplitudeClient.upgradeSharedPrefsToDB(AmplitudeClient.java:2105)
       at com.amplitude.api.AmplitudeClient.upgradeSharedPrefsToDB(AmplitudeClient.java:2088)
       at com.amplitude.api.AmplitudeClient$1.run(AmplitudeClient.java:241)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by niqo01** [comment]
same here http://crashes.to/s/af87116ac92

**Comment by niqo01** [comment]
Probably need to handle corruption smartly: https://stackoverflow.com/questions/7764943/what-can-be-done-about-the-fact-that-android-automatically-deletes-corrupt-sqlit
It would be good to at least prevent a crash due to analytic causes

**Comment by haoliu-amp** [comment]
Now we are catching it. Closed.
