### ISSUE TITLE
NPE in DeviceInfo

### ISSUE THREAD

**Issue by vishna** [amplitude/Amplitude-Android#145]
version `2.14` + emulator (no play services)

```java
E/com.amplitude.api.DeviceInfo: Encountered an error connecting to Google Play Services
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
  at com.amplitude.api.DeviceInfo$CachedInfo.getAndCacheGoogleAdvertisingId(DeviceInfo.java:214)
  at com.amplitude.api.DeviceInfo$CachedInfo.getAdvertisingId(DeviceInfo.java:194)
  at com.amplitude.api.DeviceInfo$CachedInfo.<init>(DeviceInfo.java:57)
  at com.amplitude.api.DeviceInfo$CachedInfo.<init>(DeviceInfo.java:42)
  at com.amplitude.api.DeviceInfo.getCachedInfo(DeviceInfo.java:267)
  at com.amplitude.api.DeviceInfo.prefetch(DeviceInfo.java:273)
  at com.amplitude.api.AmplitudeClient.initializeDeviceInfo(AmplitudeClient.java:306)
  at com.amplitude.api.AmplitudeClient.access$000(AmplitudeClient.java:40)
  at com.amplitude.api.AmplitudeClient$1.run(AmplitudeClient.java:243)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.os.HandlerThread.run(HandlerThread.java:61)
```

please fix

**Comment by vishna** [comment]
also I'm not sure why this happens since it's already being try catched

**Comment by vishna** [comment]
ok the issue seems to be unrelated to amplitude, sorry for the noise.

**Comment by vlazzle** [comment]
@vishna just curious, what was causing this for you? I'm seeing the same issue.

**Comment by kyuumeitai** [comment]
@vishna Did you figure it out?

**Comment by jjacobsdd** [comment]
@vishna Now, we're three.
