### ISSUE TITLE
NullPointerException when Google Play Services is missing

### ISSUE THREAD

**Issue by austynmahoney** [amplitude/Amplitude-Android#149]
SDK v2.14.0

Testing on an emulator with an older version of Google Play Services (`10298470`) and got this stack trace when I launch the app:

```
E/com.amplitude.api.DeviceInfo: Encountered an error connecting to Google Play Services
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                       at com.amplitude.api.DeviceInfo$CachedInfo.getAndCacheGoogleAdvertisingId(DeviceInfo.java:214)
                                                       at com.amplitude.api.DeviceInfo$CachedInfo.getAdvertisingId(DeviceInfo.java:194)
                                                       at com.amplitude.api.DeviceInfo$CachedInfo.<init>(DeviceInfo.java:57)
                                                       at com.amplitude.api.DeviceInfo$CachedInfo.<init>(DeviceInfo.java:42)
                                                       at com.amplitude.api.DeviceInfo.getCachedInfo(DeviceInfo.java:267)
                                                       at com.amplitude.api.DeviceInfo.prefetch(DeviceInfo.java:273)
                                                       at com.amplitude.api.AmplitudeClient.initializeDeviceInfo(AmplitudeClient.java:306)
                                                       at com.amplitude.api.AmplitudeClient.access$000(AmplitudeClient.java:40)
                                                       at com.amplitude.api.AmplitudeClient$1.run(AmplitudeClient.java:243)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by bunjix** [comment]
Hello, 
Got the same issue on my project. I'm surprised this issue is open since July and got no response :(

@austynmahoney do you find a workaround?

**Comment by FrankSalad** [comment]
Had the same issue on an emulator that stops being able to resolve DNS (it occasionally does this when my laptop wakes from sleep). Causes a crash on every app start. Quitting and restarting the emulator resolves the issue.

**Comment by andrewvolosko** [comment]
Also got same issue with 2.15.0

**Comment by djih** [comment]
@bunjix  so I think the issue is caused by proguard.

We use reflection to try and call a google play services method: https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/DeviceInfo.java#L210-L213, and I think proguard alters the name of the class / methods and the reflection causes an NPE.

I think the workaround is to whitelist/exclude the google play service methods in proguard?

**Comment by andrewvolosko** [comment]
@djih all play services? 
Maybe you can point to part/module that you are using via reflection.

I saw in amplitude samples/doc only this rule that relates
keep class com.google.android.gms.ads.** { *; }

**Comment by djih** [comment]
@andrewvolosko so we're trying to use `com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo()`, which should be covered by that rule? Although that's exactly what's throwing the NPE :\
