### ISSUE TITLE
SecurityException in com.amplitude.api.DeviceInfo

### ISSUE THREAD

**Issue by auf1r2** [amplitude/Amplitude-Android#158]
Samsung Galaxy Tab2 7.0, Android 4.1.1
I see following stack trace from one of my users. Repeated constantly for this one user. Any ideas guys?
```
Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.android.location.service.GeocodeProvider pkg=com.google.android.location }
       at android.os.Parcel.readException(Parcel.java:1425)
       at android.os.Parcel.readException(Parcel.java:1379)
       at android.location.ILocationManager$Stub$Proxy.getFromLocation(ILocationManager.java:971)
       at android.location.Geocoder.getFromLocation(Geocoder.java:133)
       at com.amplitude.api.DeviceInfo$CachedInfo.getCountryFromLocation(DeviceInfo.java:137)
       at com.amplitude.api.DeviceInfo$CachedInfo.getCountry(DeviceInfo.java:115)
       at com.amplitude.api.DeviceInfo$CachedInfo.(DeviceInfo.java:65)
       at com.amplitude.api.DeviceInfo$CachedInfo.(DeviceInfo.java:42)
       at com.amplitude.api.DeviceInfo.getCachedInfo(DeviceInfo.java:262)
       at com.amplitude.api.DeviceInfo.getAdvertisingId(DeviceInfo.java:312)
       at com.amplitude.api.AmplitudeClient.initializeDeviceId(AmplitudeClient.java:1904)
       at com.amplitude.api.AmplitudeClient.initializeDeviceInfo(AmplitudeClient.java:305)
       at com.amplitude.api.AmplitudeClient.access$000(AmplitudeClient.java:40)
       at com.amplitude.api.AmplitudeClient$1.run(AmplitudeClient.java:243)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by haoliu-amp** [comment]
Did you add the location permission to your `AndroidManifest.xml`?
