### ISSUE TITLE
getMostRecentLocation causing NullPointerException

### ISSUE THREAD

**Issue by berglind** [amplitude/Amplitude-Android#16]
From our crash logs
```
java.lang.NullPointerException
	at com.amplitude.api.DeviceInfo.getMostRecentLocation(Unknown Source)
	at com.amplitude.api.Amplitude.logEvent(Unknown Source)
                                logEvent
                                logEvent
                                logEvent
	at com.amplitude.api.Amplitude.access$1300(Unknown Source)
	at com.amplitude.api.Amplitude$2.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:605)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by allanca** [comment]
While I wasn't able to explicitly reproduce the crash, I've added tests for null on the edge cases that will fix this crash. The fix will be included in the next release of the SDK.
