### ISSUE TITLE
No static method domainToAscii(Ljava/lang/String;)

### ISSUE THREAD

**Issue by OneXeor** [amplitude/Amplitude-Android#168]
Hi, can anyone help me with this issue?

 java.lang.NoSuchMethodError: No static method domainToAscii(Ljava/lang/String;)Ljava/lang/String; in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/com.example.package-lGF3tC_KeJfEj0ek8ZxAMg==/split_lib_directories_apk.apk!classes2.dex)
        at okhttp3.HttpUrl$Builder.canonicalizeHost(HttpUrl.java:1597)
        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1395)
        at okhttp3.HttpUrl.parse(HttpUrl.java:902)
        at okhttp3.Request$Builder.url(Request.java:142)
        at com.amplitude.api.AmplitudeClient.makeEventUploadPostRequest(AmplitudeClient.java:1808)
        at com.amplitude.api.AmplitudeClient$13.run(AmplitudeClient.java:1689)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by 7va** [comment]
Same bug

**Comment by haoliu-amp** [comment]
@OneXeor , @7va  Can you try to use 2.24.2? https://mvnrepository.com/artifact/com.amplitude/android-sdk/2.24.2
