### ISSUE TITLE
Diagnostics crash on android 9

### ISSUE THREAD

**Issue by krcho** [amplitude/Amplitude-Android#194]
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:733)
       at com.amplitude.api.Diagnostics.(SourceFile:58)
       at com.amplitude.api.Diagnostics.getLogger(SourceFile:47)
       at com.amplitude.api.AmplitudeClient.updateServer(SourceFile:1793)
       at com.amplitude.api.AmplitudeClient$12.run(SourceFile:1783)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:65)

so many crashes on android 9.
plz check it

**Comment by krcho** [comment]
my SDK version is 2.22.0

**Comment by kapilsukhyani** [comment]
We are also facing this at Atlassian

**Comment by djih** [comment]
@krcho @kapilsukhyani thanks for reporting, we are investigating. Initially it looks like our SDK is being initialized very late, like on app close, and when it initializes it starts a few background threads. The solution would be to not start the threads in this case? Also the crash happens when the app is already in the process of shutting down, so perhaps it is not impacting user experience, but still worth investigating.

Other similar threads:
https://github.com/square/okhttp/issues/1153
https://github.com/facebook/fresco/issues/1144
https://github.com/OneSignal/OneSignal-Android-SDK/issues/443

**Comment by haoliu-amp** [comment]
We removed this class.
