### ISSUE TITLE
[CRASH] DeviceInfo.getMostRecentLocation - DeadSystemException

### ISSUE THREAD

**Issue by BaptisteRFoxIntel** [amplitude/Amplitude-Android#204]
Crash received from firebase

Amplitude SDK Version : `2.23.2`

```
Fatal Exception: java.lang.RuntimeException: android.os.DeadSystemException
       at android.location.LocationManager.getProviders(LocationManager.java:364)
       at com.amplitude.api.DeviceInfo.getMostRecentLocation(DeviceInfo.java:361)
       at com.amplitude.api.DeviceInfo$CachedInfo.getCountryFromLocation(DeviceInfo.java:138)
       at com.amplitude.api.DeviceInfo$CachedInfo.getCountry(DeviceInfo.java:121)
       at com.amplitude.api.DeviceInfo$CachedInfo.<init>(DeviceInfo.java:64)
       at com.amplitude.api.DeviceInfo$CachedInfo.<init>(DeviceInfo.java:41)
       at com.amplitude.api.DeviceInfo.getCachedInfo(DeviceInfo.java:285)
       at com.amplitude.api.DeviceInfo.prefetch(DeviceInfo.java:291)
       at com.amplitude.api.AmplitudeClient$1.run(AmplitudeClient.java:272)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

```
Brand: motorola
Model: Moto G (5th Gen)
Orientation: Portrait
RAM free: 681.07 MB
Disk free: 1.43 GB
Version: 8.1.0
Orientation: Portrait
Rooted: No
```

**Comment by BaptisteRFoxIntel** [comment]
Happening several times... any update ?

**Comment by BaptisteRFoxIntel** [comment]
Damn...

**Comment by haoliu-amp** [comment]
@BaptisteRFoxIntel Oh! Really sorry about this, will look into it soon after finishing other priorities.

**Comment by haoliu-amp** [comment]
Hello,

Sorry for taking so long. I wonder how many bugs were reported because of this?

**Comment by BaptisteRFoxIntel** [comment]
Hello,
Last occurrences were in December.

eg
Brand: samsung
Model: Galaxy S7
Orientation: Portrait
RAM free: 1.46 GB
Disk free: 12.52 GB
Version: 8.0.0
Orientation: Portrait
Rooted: No

Seems that it did not happen with the `2.24.2` which we use since then.
I guess we could close the issue. Will reopen it if it happens again

**Comment by haoliu-amp** [comment]
@BaptisteRFoxIntel Thank you! I think it might be related to certain devices or OS. Thanks for you reporting this! And sorry for the delay.
