### ISSUE TITLE
Crash on android 4.1

### ISSUE THREAD

**Issue by kumold** [amplitude/Amplitude-Android#205]
Amplitude version 2.23.2
Error:

>  E/UncaughtException: java.lang.NoClassDefFoundError: java.util.Objects
        at okhttp3.Address.hashCode(Address.kt:180)
        at okhttp3.Route.hashCode(Route.kt:84)
        at java.util.HashMap.containsKey(HashMap.java:327)
        at java.util.HashSet.contains(HashSet.java:138)
        at okhttp3.internal.connection.RouteDatabase.shouldPostpone(RouteDatabase.kt:40)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:74)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:199)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at com.amplitude.api.AmplitudeClient.makeEventUploadPostRequest(AmplitudeClient.java:1966)
        at com.amplitude.api.AmplitudeClient$13.run(AmplitudeClient.java:1831)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)
11-07 12:19:50.597 3275-3340 E/AndroidRuntime: FATAL EXCEPTION: httpThread
    java.lang.NoClassDefFoundError: java.util.Objects
        at okhttp3.Address.hashCode(Address.kt:180)
        at okhttp3.Route.hashCode(Route.kt:84)
        at java.util.HashMap.containsKey(HashMap.java:327)
        at java.util.HashSet.contains(HashSet.java:138)
        at okhttp3.internal.connection.RouteDatabase.shouldPostpone(RouteDatabase.kt:40)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:74)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:199)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at com.amplitude.api.AmplitudeClient.makeEventUploadPostRequest(AmplitudeClient.java:1966)
        at com.amplitude.api.AmplitudeClient$13.run(AmplitudeClient.java:1831)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by kumold** [comment]
Same errors on android 4.4
