### ISSUE TITLE
App crashes with Amplitude sdk, when device returns null location providers

### ISSUE THREAD

**Issue by marekkondracki** [amplitude/Amplitude-Android#243]
Running app on device without location provider causing crash:
```
java.lang.NullPointerException
        at android.location.LocationManager.getProviders(LocationManager.java:343)
        at com.amplitude.api.DeviceInfo.getMostRecentLocation(DeviceInfo.java:353)
        at com.amplitude.api.DeviceInfo$CachedInfo.getCountryFromLocation(DeviceInfo.java:140)
        at com.amplitude.api.DeviceInfo$CachedInfo.getCountry(DeviceInfo.java:123)
        at com.amplitude.api.DeviceInfo$CachedInfo.<init>(DeviceInfo.java:65)
        at com.amplitude.api.DeviceInfo$CachedInfo.<init>(DeviceInfo.java:42)
        at com.amplitude.api.DeviceInfo.getCachedInfo(DeviceInfo.java:273)
        at com.amplitude.api.DeviceInfo.prefetch(DeviceInfo.java:279)
        at com.amplitude.api.AmplitudeClient.lambda$initialize$0$AmplitudeClient(AmplitudeClient.java:275)
        at com.amplitude.api.-$$Lambda$AmplitudeClient$9hxT9i3yp7eOymOvTMj42XcPKBs.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

The problem is that NPE is not caught in DeviceInfo class. [https://github.com/amplitude/Amplitude-Android/blob/master/src/main/java/com/amplitude/api/DeviceInfo.java](https://github.com/amplitude/Amplitude-Android/blob/master/src/main/java/com/amplitude/api/DeviceInfo.java)

```
        List<String> providers = null;
        try {
            providers = locationManager.getProviders(true);
        } catch (SecurityException e) {
            // failed to get providers list
        }
```
Changing SecurityException to Exception will solve problem.

**Comment by haoliu-amp** [comment]
Thank you for reporting! It's fixed in this PR #245
