### ISSUE TITLE
Question about disableLocationListening()

### ISSUE THREAD

**Issue by xgear-public** [amplitude/Amplitude-Android#248]
Hello!
I found in [docs](http://amplitude.github.io/Amplitude-Android/com/amplitude/api/AmplitudeClient.html#disableLocationListening--) for this method following description:

> Disable location listening in the SDK. This will stop the sending of the user's current lat/lon coordinates. This function should be called before SDK initialization, e.g. initialize(Context, String).

>This function should be called before SDK initialization

When i call it before i am getting exception:

                Amplitude.getInstance()
                        .disableLocationListening();

                Amplitude.getInstance()
                        .initialize(
                        app.getApplicationContext(),
                        platformsDebugMode ? amplitudeApiKeyDev : amplitudeApiKeyProd
                )
                        .setServerUrl("https://api2.amplitude.com")
                        .setLogLevel(platformsDebugMode ? Log.VERBOSE : Log.WARN)
                        .enableLogging(platformsDebugMode)
                        .enableForegroundTracking(app)
                        .setTrackingOptions(options);

> 2020-08-20 20:44:52.576 9251-9426/ E/AndroidRuntime: FATAL EXCEPTION: logThread
    java.lang.IllegalStateException: Must initialize before acting on location listening.
        at com.amplitude.api.AmplitudeClient$3.run(AmplitudeClient.java:422)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)

Could you please help to fix it?

**Comment by xgear-public** [comment]
Sorry, I found issue, my fault, please close issue.
