### ISSUE TITLE
com.amplitude.api.ConfigManager.refresh: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by enginegl** [amplitude/Amplitude-Android#256]
We've noticed a new trending crash in production:
```
java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192
        at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:818)
        at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:793)
        at com.android.okhttp.okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:59)
        at com.android.okhttp.internal.http.Http1xStream.writeRequest(Http1xStream.java:167)
        at com.android.okhttp.internal.http.Http1xStream.writeRequestHeaders(Http1xStream.java:123)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:617)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:482)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:549)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
        at com.amplitude.api.ConfigManager.refresh(ConfigManager:32)
        at com.amplitude.api.AmplitudeClient$6.run(AmplitudeClient:1375)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

## Possible Solution
Handle such exceptions in `com.amplitude.api.ConfigManager::refresh` method to prevent a crash of a host app.

The current implementation doesn't catch such exceptions:
```java
    public void refresh(RefreshListener listener) {
        try {
            ...
        } catch (MalformedURLException e) {

        } catch (IOException e) {

        } catch (JSONException e) {

        }

        listener.onFinished();
    }
```

## Environment
- SDK Version: 2.29.1
- Android API Level: Multiple versions: 7.0, 8.0, 8.1.0, 9
- Device: Multiple vendors including Xiaomi, Oppo, Huawei, Motorola, Vivo

**Comment by haoliu-amp** [comment]
Thanks for reporting! Fixed in #257
