### ISSUE TITLE
Crash: Internal Error

### ISSUE THREAD

**Issue by sauniksingh** [amplitude/Amplitude-Android#260]
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:730)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
       at com.google.firebase.perf.transport.TransportManager.log(TransportManager.java:323)
       at com.google.firebase.perf.impl.NetworkRequestMetricBuilder.build(NetworkRequestMetricBuilder.java:338)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.sendNetworkMetric(FirebasePerfOkHttpClient.java:108)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(FirebasePerfOkHttpClient.java:45)
       at com.amplitude.api.AmplitudeClient.makeEventUploadPostRequest(AmplitudeClient.java:2081)
       at com.amplitude.api.AmplitudeClient$12.run(AmplitudeClient.java:1946)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.os.HandlerThread.run(HandlerThread.java:61) 

## Possible Solution
It should be run in worker thread

## Environment
- SDK Version: 7.0
- Android API Level: 24
- Device: vivo 1714

**Comment by haoliu-amp** [comment]
Hello, have you added the okhttp dependency? https://developers.amplitude.com/docs/android#1-add-dependencies

**Comment by dantetam** [comment]
Closed because this is stale. Feel free to reopen with more info or concerns.
