### ISSUE TITLE
TaskRunner.java line 299

### ISSUE THREAD

**Issue by sauniksingh** [amplitude/Amplitude-Android#261]
```
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:883)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1393)
       at okhttp3.internal.concurrent.TaskRunner$RealBackend.execute(TaskRunner.java:299)
       at okhttp3.internal.concurrent.TaskRunner.kickCoordinator$okhttp(TaskRunner.java:92)
       at okhttp3.internal.concurrent.TaskQueue.schedule(TaskQueue.java:73)
       at okhttp3.internal.concurrent.TaskQueue.execute$default(TaskQueue.java:96)
       at okhttp3.internal.http2.Http2Connection.writeSynResetLater$okhttp(Http2Connection.java:1014)
       at okhttp3.internal.http2.Http2Stream.closeLater(Http2Stream.java:250)
       at okhttp3.internal.http2.Http2ExchangeCodec.cancel(Http2ExchangeCodec.java:122)
       at okhttp3.internal.connection.Exchange.detachWithViolence(Exchange.java:161)
       at okhttp3.internal.connection.RealCall.exitNetworkInterceptorExchange$okhttp(RealCall.java:424)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:133)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
       at okhttp3.internal.connection.RealCall.execute(RealCall.java:154)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(FirebasePerfOkHttpClient.java:43)
       at com.amplitude.api.AmplitudeClient.makeEventUploadPostRequest(AmplitudeClient.java:2081)
       at com.amplitude.api.AmplitudeClient$12.run(AmplitudeClient.java:1946)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:230)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

## Environment
- SDK Version: Android 10
- Android API Level: 29
- Device: vivo 1938

**Comment by dantetam** [comment]
Hello @sauniksingh ,

Sorry for the late reply. If you are still working on this, could you provide me the steps and code to reproduce this error?

Thanks,
Dante

**Comment by dantetam** [comment]
Closed because this is stale. Feel free to reopen with more info or concerns.

This is also a duplicate. I cannot reproduce this without more info.
