### ISSUE TITLE
ResourceNotFoundException

### ISSUE THREAD

**Issue by NathanAndrade** [amplitude/Amplitude-Android#262]
Firebase Crashlytics tool is capturing this error so much

`Fatal Exception: android.content.res.Resources$NotFoundException: String resource ID #0x10401f4
       at android.content.res.Resources.getText(Resources.java:367)
       at android.content.res.Resources.getString(Resources.java:460)
       at android.database.sqlite.SQLiteGlobal.getDefaultJournalMode(SQLiteGlobal.java:89)
       at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:317)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:915)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:759)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:748)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
       at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:341)
       at com.amplitude.api.DatabaseHelper.getValueFromTable(DatabaseHelper.java:279)
       at com.amplitude.api.DatabaseHelper.getValue(DatabaseHelper.java:268)
       at com.amplitude.api.AmplitudeClient.lambda$initialize$0$AmplitudeClient(AmplitudeClient.java:291)
       at com.amplitude.api.-$$Lambda$AmplitudeClient$9NDt_YKBCJ8Ih0Ic4HFC4DZmSRA.run(:8)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:241)
       at android.os.HandlerThread.run(HandlerThread.java:67)`

**Comment by dantetam** [comment]
Hello @NathanAndrade ,

Apologies for the late reply. 

This seems like a problem with Android resource management. References to assets in an Android app like `R.drawable.resourcename` are failing, or Android UI elements like `textView.setText(R.string.resourcename)` working with such assets are referencing incorrectly.

If you are still having the issue, could you please show the organization of your Android resource folders and any Amplitude code that deals with Android resources?

Thanks,
Dante

**Comment by haoliu-amp** [comment]
Doesn't look it's our issue.
