### ISSUE TITLE
Crashes: Fatal Exception: android.database.CursorWindowAllocationException

### ISSUE THREAD

**Issue by vitalii-rudenko** [amplitude/Amplitude-Android#283]
Sometimes our app randomly crashes with the exception:
We use com.amplitude:android-sdk:2.30.2

```
Fatal Exception: android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0/video.reface.app/databases/com.amplitude.api' of size 2097152 due to error -12.
       at android.database.CursorWindow.nativeCreate(CursorWindow.java)
       at android.database.CursorWindow.<init>(CursorWindow.java:139)
       at android.database.CursorWindow.<init>(CursorWindow.java:120)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:202)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
       at com.amplitude.api.DatabaseHelper.getEventsFromTable(DatabaseHelper.java:331)
       at com.amplitude.api.DatabaseHelper.getEvents(DatabaseHelper.java:311)
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:1929)
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:1901)
       at com.amplitude.api.AmplitudeClient$11.run(AmplitudeClient.java:1892)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by AlfonChitoSalano** [comment]
This is also happening to us.

**Comment by thisisthekap** [comment]
@dantetam According to our research, a proper closing of QueryDB (cursor) of sqlite might be missing. Also see https://stackoverflow.com/a/6075632 for reference.

**Comment by runaloop** [comment]
Hey guys, any news on this problem? I see this crash also on my project.

**Comment by runaloop** [comment]
@ajhorst any news on when this fix will be available?

**Comment by yuhao900914** [comment]
Hi @runaloop ,
We will release the changes soon.
