### ISSUE TITLE
Fatal Exception: android.database.CursorWindowAllocationException

### ISSUE THREAD

**Issue by akshaymanathkar** [amplitude/Amplitude-Android#286]
## Expected Behavior
Crashlytics for our App reporting this error a lot
following is the crash log

Fatal Exception: android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0/my.app.package.name/databases/com.amplitude.api' of size 4194304 due to error -12.
       at android.database.CursorWindow.nativeCreate(CursorWindow.java)
       at android.database.CursorWindow.<init>(CursorWindow.java:145)
       at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:319)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:159)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:152)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
       at com.amplitude.api.DatabaseHelper.getEventsFromTable(DatabaseHelper.java:367)
       at com.amplitude.api.DatabaseHelper.getEvents(DatabaseHelper.java:347)
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:1814)
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:1785)
       at com.amplitude.api.AmplitudeClient$11.run(AmplitudeClient.java:1762)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.os.HandlerThread.run(HandlerThread.java:67)

## Steps to Reproduce
 

1.
2.
3.
4.

## Environment
- SDK Version: 
- Android API Level: 
- Device:

**Comment by dantetam** [comment]
For anyone else who is reading and for our own internal eng. records, this was fixed in https://github.com/amplitude/Amplitude-Android/pull/285
