### ISSUE TITLE
📣 Introducing Amplitude Android Kotlin SDK [BETA]

### ISSUE THREAD

**Issue by qingzhuozhen** [amplitude/Amplitude-Android#336]
<p align="center">
  <a href="https://amplitude.com" target="_blank" align="center">
    <img src="https://static.amplitude.com/lightning/46c85bfd91905de8047f1ee65c7c93d6fa9ee6ea/static/media/amplitude-logo-with-text.4fb9e463.svg" width="280">
  </a>
  <br />
</p>

# Announcement

Amplitude is introducing a new [Kotlin SDK for Android](https://github.com/amplitude/Amplitude-Kotlin) [BETA]. This new SDK provides improved developer experience, helps users instrument data more seamlessly and provide more control over data being instrumented using custom plugins. The new SDKs also comes with:

* Custom plugins
* Built-in type definitions
* No SQLite and Okhttp dependency

To learn more about the new SDK, here are some useful links:

* Maven: https://search.maven.org/artifact/com.amplitude/analytics-android
* GitHub: https://github.com/amplitude/Amplitude-Kotlin
* Documentation: https://developers.amplitude.com/docs/kotlin-android-beta

Feel free to check it out and share any feedback!

**Comment by mahmoudElfeel67** [comment]
@qingzhuozhen i am have a crash updating from the old to new library 

`Caused by android.system.ErrnoException: open failed: ENOENT (No such file or directory)
       at libcore.io.Linux.open(Linux.java)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
       at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7747)
       at libcore.io.IoBridge.open(IoBridge.java:478)
       at java.io.FileInputStream.<init>(FileInputStream.java:160)
       at com.amplitude.android.utilities.AndroidStorage.getEventsString(AndroidStorage.kt:65)
       at com.amplitude.core.platform.EventPipeline$upload$1.invokeSuspend(EventPipeline.kt:106)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)`

**Comment by justin-fiedler** [comment]
Hi @mahmoudElfeel67 can you please check what version of the SDK you are using. This issue should be fixed in `1.0.1` and above. Hopefully updating to the latest version `1.13.0` will fix the bug. Thanks!
https://github.com/amplitude/Amplitude-Kotlin/releases
