### ISSUE TITLE
NullPointerException : DeviceInfo.getVersionName

### ISSUE THREAD

**Issue by gsrathoreniks** [amplitude/Amplitude-Android#347]
## Current Behavior
Throwing NullPointerExceptions for `getVersionName()`
```
Non-fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'i3.q$a i3.q.b()' on a null object reference
       at com.amplitude.api.DeviceInfo.getVersionName(DeviceInfo.java:287)
       at com.amplitude.api.AmplitudeClient.logEvent(AmplitudeClient.java:1010)
       at com.amplitude.api.AmplitudeClient.logEventSync(AmplitudeClient.java:885)
       at com.amplitude.api.AmplitudeClient.logEventSync(AmplitudeClient.java:867)
       at com.amplitude.api.AmplitudeClient.logEventSync(AmplitudeClient.java:831)
       at com.amplitude.api.AmplitudeClient.logEventSync(AmplitudeClient.java:816)
```

## Steps to Reproduce
 

1. Logging events to amplitude, no specific steps.

## Environment
- SDK Version: `2.26.0`
- Android API Level: ALL
- Device: ALL

**Comment by liuyang1520** [comment]
Hi @gsrathoreniks , thanks for supporting us!

I noticed you are using an old version of this legacy Android SDK, our latest version is 2.38.3 and we have a lot of changes in between: https://github.com/amplitude/Amplitude-Android/compare/v2.26.0...main. Could you try the latest version?

Thanks!

**Comment by kevinpagtakhan** [comment]
Hi @gsrathoreniks did the new version help at all? Thank you

**Comment by liuyang1520** [comment]
Closing this due to inactivity.
