### ISSUE TITLE
Crash: Could not allocate CursorWindow

### ISSUE THREAD

**Issue by chengtin-tsai** [amplitude/Amplitude-Android#374]
## Current Behavior

This crash happened after we upgraded the SDK from 2.28.2 to 2.39.5.
It might relate to #285 
```
Fatal Exception: t7.q: Could not allocate CursorWindow '/data/user/0/com.particlenews.newsbreak/databases/com.amplitude.api' of size 2097152 due to error -12.
       at com.amplitude.api.DatabaseHelper.convertIfCursorWindowException(DatabaseHelper.java:587)
       at com.amplitude.api.DatabaseHelper.getEventsFromTable(DatabaseHelper.java:373)
       at com.amplitude.api.DatabaseHelper.getIdentifyInterceptors(DatabaseHelper.java:338)
       at com.amplitude.api.IdentifyInterceptor.getTransferIdentifyEvent(IdentifyInterceptor.java:118)
       at com.amplitude.api.IdentifyInterceptor.transferInterceptedIdentify(IdentifyInterceptor.java:150)
       at com.amplitude.api.IdentifyInterceptor.intercept(IdentifyInterceptor.java:81)
       at com.amplitude.api.AmplitudeClient.saveEvent(AmplitudeClient.java:1360)
       at com.amplitude.api.AmplitudeClient.logEvent(AmplitudeClient.java:1323)
       at com.amplitude.api.AmplitudeClient$4.run(AmplitudeClient.java:1182)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

## Steps to Reproduce
 

1.
2.
3.
4.

## Environment
- SDK Version:  v2.39.5
- Android API Level:  71% Android 10, 26% Android 11
- Device:  37% ZTE Z6250CC, 24% BLU - Mediatek B131DL, 21% TCT Mobile Limited (Alcatel)

**Comment by justin-fiedler** [comment]
Hi @chengtin-tsai we released a potential fix in [v2.39.7](https://github.com/amplitude/Amplitude-Android/releases/tag/v2.39.7). Hope this helps!
