### ISSUE TITLE
Can't downgrade database from version 4 to 3

### ISSUE THREAD

**Issue by ravenfeld** [amplitude/Amplitude-Android#391]
Hello, I'm trying to migrate to Ampli but I have a problem with the init.
`getValue from store failed
android.database.sqlite.SQLiteException: Can't downgrade database from version 4 to 3
at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:553)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414)
at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
at com.amplitude.api.DatabaseHelper.getValueFromTable(DatabaseHelper.java:279)
at com.amplitude.api.DatabaseHelper.getValue(DatabaseHelper.java:268)
at com.amplitude.api.AmplitudeClient.initializeDeviceId(AmplitudeClient.java:2315)
at com.amplitude.api.AmplitudeClient.lambda$initializeInternal$1$com-amplitude-api-AmplitudeClient(AmplitudeClient.java:366)
at com.amplitude.api.AmplitudeClient$$ExternalSyntheticLambda0.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.os.HandlerThread.run(HandlerThread.java:67)`

I guess that's why we don't have any more events coming up.

Thank you in advance for your help.

## Environment
- SDK Version: 1.14.0
- Android API Level: 14
- Device: Pixel 7

**Comment by ravenfeld** [comment]
Worry if you switch from ampli and go back to the sdk version.
