### ISSUE TITLE
SQLiteException on open DB

### ISSUE THREAD

**Issue by philippb** [amplitude/Amplitude-Android#4]
**Android 2.3.3 - 2.3.7**

`android.database.sqlite.SQLiteException: unable to open database file
at android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
at android.database.sqlite.SQLiteDatabase.<init>(SQLiteDatabase.java:1851)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:822)
at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:856)
at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:849)
at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:562)
at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:203)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:118)
at com.amplitude.api.DatabaseHelper.addEvent(DatabaseHelper.java:48)
at com.amplitude.api.Amplitude$1.run(Amplitude.java:160)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at com.amplitude.api.DatabaseThread.run(DatabaseThread.java:26)`

**Comment by rohitramkumar308** [comment]
I know this is too late but found the solution use compile 'com.google.android.gms:play-services-safetynet:8.1.0' in your gradle. It takes care of the OS version and uses the appropriate SQLite version
