### ISSUE TITLE
Amplitude crashing the process

### ISSUE THREAD

**Issue by schwiz** [amplitude/Amplitude-Android#45]
Here is the stacktrace from version 1.6.3

       java.lang.NoSuchMethodError: Llibcore/net/UriCodec;.
       at libcore.net.UriCodec.(UriCodec.java:109)
       at libcore.net.UriCodec.encode(UriCodec.java:133)
       at java.net.URLEncoder.encode(URLEncoder.java:57)
       at com.squareup.okhttp.FormEncodingBuilder.add(FormEncodingBuilder.java:40)
       at com.amplitude.api.AmplitudeClient.makeEventUploadPostRequest(AmplitudeClient.java:627)
       at com.amplitude.api.AmplitudeClient$9.run(AmplitudeClient.java:596)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by djih** [comment]
@schwiz are you still seeing this crash?

**Comment by djih** [comment]
This should have been fixed by us switching to Okhttp3
