### ISSUE TITLE
java.lang.NoSuchMethodError DeviceInfo

### ISSUE THREAD

**Issue by osipovas** [amplitude/Amplitude-Android#62]
Stack Trace:
`
java.lang.NoSuchMethodError: Landroid/location/Geocoder;.<init>
       at com.amplitude.api.DeviceInfo.getGeocoder(DeviceInfo.java:83)
       at com.amplitude.api.DeviceInfo.getCountryFromLocation(DeviceInfo.java:92)
       at com.amplitude.api.DeviceInfo.getCountryUncached(DeviceInfo.java:130)
       at com.amplitude.api.DeviceInfo.getCountry(DeviceInfo.java:76)
       at com.amplitude.api.AmplitudeClient$1.run(AmplitudeClient.java:143)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)
`

Amplitude Library Version: 1.7.0
Device: SPH-L720 (Rooted)

I don't have access to the device, this is information from our crash reporting tool.

In the most recent version (2.0.2) of the SDK both IOException and NullPointerException are caught, but not NoSuchMethodError or a super class of it.

**Comment by djih** [comment]
Thanks for bringing this to our attention. We will have a patch in our next release.

**Comment by djih** [comment]
This issue is fixed with v2.0.4: https://github.com/amplitude/Amplitude-Android/releases/tag/v2.0.4
