### ISSUE TITLE
java.lang.IllegalArgumentException DeviceInfo

### ISSUE THREAD

**Issue by osipovas** [amplitude/Amplitude-Android#63]
Stack Trace:
java.lang.IllegalArgumentException
       at android.os.Parcel.readException(Parcel.java:1544)
       at android.os.Parcel.readException(Parcel.java:1493)
       at android.location.ILocationManager$Stub$Proxy.getLastLocation(ILocationManager.java:734)
       at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1232)
       at com.amplitude.api.DeviceInfo.getMostRecentLocation(DeviceInfo.java:196)
       at com.amplitude.api.DeviceInfo.getCountryFromLocation(DeviceInfo.java:89)
       at com.amplitude.api.DeviceInfo.getCountryUncached(DeviceInfo.java:130)
       at com.amplitude.api.DeviceInfo.getCountry(DeviceInfo.java:76)
       at com.amplitude.api.AmplitudeClient$1.run(AmplitudeClient.java:143)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)

Amplitude Library Version: 1.7.0
Device: SAMSUNG-SM-G920A (non-rooted)
Android Version: 5.0.2

I don't have access to the device, this is information from our crash reporting tool.

**Comment by djih** [comment]
Thank you for bringing this to our attention. The patch is here: https://github.com/amplitude/Amplitude-Android/commit/d505dd7bf5aeec6f082c307a0951ef30e139785c, and will be in the next release

**Comment by djih** [comment]
This is released with [v2.2.0](https://github.com/amplitude/Amplitude-Android/releases/tag/v2.2.0), might take a few hours to appear on Maven Central
