### ISSUE TITLE
Getting OutofMemoryError in AmplitudeClient in updateServer operation

### ISSUE THREAD

**Issue by kshark27** [amplitude/Amplitude-Android#93]
Hi Team,
Please check this error. 
Fatal Exception: java.lang.OutOfMemoryError
       at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
       at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:132)
       at java.lang.StringBuilder.append(StringBuilder.java:124)
       at org.json.JSONStringer.string(JSONStringer.java:344)
       at org.json.JSONStringer.key(JSONStringer.java:375)
       at org.json.JSONObject.writeTo(JSONObject.java:667)
       at org.json.JSONStringer.value(JSONStringer.java:237)
       at org.json.JSONArray.writeTo(JSONArray.java:572)
       at org.json.JSONArray.toString(JSONArray.java:544)
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:811)
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:789)
       at com.amplitude.api.AmplitudeClient$7.run(AmplitudeClient.java:783)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:177)
       at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by djih** [comment]
Hi @kshark27 , apologies for the crashes. Are you able to replicate the crash? Any other deatils? Is your app memory-intensive? The crash is happening when the SDK tries to JSON serialize the events to send to our servers. By default it sends up to 30 events with each request. What you can try to do is set a smaller batch size (something like 15 or even 10):

`Amplitude.getInstance().setEventUploadMaxBatchSize(15);`

**Comment by kshark27** [comment]
Yes djih, Ours is a video streaming app so you can say its memory-intensive. Another weird thing I noticed, While sending an empty JSONObject, the event can be seen on events timeline but while sending a JSONObject with multiple attributes, the events are not recorded at all.

For an example 
// LoginSkip event is recorded
```
public static void loginSkip(Context context) {
        JSONObject eventData=new JSONObject();
        sendEvent(context, LOGIN_SKIP, eventData);
    }
```

// TrackMediaClick event is not recorded

```
public static void trackMediaClick(Context mContext,int networktype,String mediaId, String mediaName ){
        JSONObject eventData=new JSONObject();
        try{
            eventData.put(MEDIA_ID,mediaId);
            eventData.put(MEDIA_TITLE,mediaName);
        }catch (JSONException e){
            e.printStackTrace();
        }
        if(networktype==PRESSPLAY_NETWORK){
            sendEvent(mContext,PPN_OFFLINE_MEDIA_CLICK,eventData);
        }else {
            sendEvent(mContext,NONPPN_OFFLINE_MEDIA_CLICK,eventData);
        }

    }

```

**Comment by djih** [comment]
@kshark27 : since your app is memory-intensive, I recommend setting a smaller event upload batch size, so that our SDK sends events in smaller batches (using less memory to generate JSON string). You could try a threshold like 10: `Amplitude.getInstance().setEventUploadMaxBatchSize(10);`

Regarding the events, could it be a format thing? I'm wondering if our servers might be rejecting your event for some formatting thing. Can you debug your app during the process of sending events? Inside AmplitudeClient, there's a `makeEventUploadPostRequest` method, and it will call these lines: 
```Response response = client.newCall(request).execute();
   String stringResponse = response.body().string();
   if (stringResponse.equals("success")) {```

Can you see what the response body and code are? Any errors? In normal cases you should be getting a 200/success.

Could it be that the OOM crashes are causing your event upload to fail so that's why you aren't seeing your events?
