### ISSUE TITLE
ndroid.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed.

### ISSUE THREAD

**Issue by darshana-ios** [amplitude/Amplitude-Android#94]
Fatal Exception: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
       at android.database.CursorWindow.<init>(CursorWindow.java:108)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
       at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:316)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:142)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:136)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
       at com.amplitude.api.DatabaseHelper.getValueFromTable(DatabaseHelper.java:199)
       at com.amplitude.api.DatabaseHelper.getLongValue(DatabaseHelper.java:184)
       at com.amplitude.api.AmplitudeClient.getNextSequenceNumber(AmplitudeClient.java:431)
       at com.amplitude.api.AmplitudeClient.logEvent(AmplitudeClient.java:361)
       at com.amplitude.api.AmplitudeClient$2.run(AmplitudeClient.java:317)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by djih** [comment]
@darshana-ios thank you for reporting. Are you able to replicate the crash? Any more details you can provide? As far as I know we are closing all of our cursors correctly. This might be an OOM error?

**Comment by djih** [comment]
@darshana-ios we haven't had any other reports of this issue. If you look at our code here: https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/DatabaseHelper.java#L203-L266, you will see that we only use cursors in 2 methods `getEventsFromTable` and `getValueFromTable`, and we close the cursors in the finally block in each method. Is it possible that your app has unclosed cursors? You need to remember to close cursors even after handling exceptions, which is why we do it in the finally block.
